services:
  web:
    restart: always
    depends_on: 
      - api
    build: ./gui
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: rebuild
          path: ./gui
          target: ./app
    

  api: 
    build: ./fastApi
    ports: 
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: ./fastApi
          target: ./app
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
